### ISSUE TITLE
how to run this blip.lua on GTA 5 SP

### ISSUE THREAD

**Issue by shamim4s** [PeEcEeChIP/Raccoons-Blips#1]
How can i run this blip.lua script on GTA5 SP offline without fivem ?
want to play this script on offline .

Best regards
Shamim

**Comment by NokaAngel** [comment]
Hey @shamim4s appreciate you for reaching out, unfortunately at this time it only supports FiveM since FiveM uses .lua, .js, & C#.

So unfortunately this only works for FiveM, I may find a way to get this to work in Singleplayer but at the moment only supports FiveM.

- PeEcEeChIP
